### ISSUE TITLE
Loginwithcompletion is not finishing , after google login it redirects to google home page

### ISSUE THREAD

**Issue by billyurs** [alexziskind1/nativescript-oauth2#67] opened 2019-09-29 11:30 UTC
export function configureOAuthProviders() {
  console.log('Configuring auth');
  const googleProvider = configureOAuthProviderGoogle();
  configureTnsOAuth([googleProvider])
}

export function tnsOauthLogin(providerType) {
  const client = new TnsOAuthClient(providerType);
  console.log(client)
  console.log('calling')
  client.loginWithCompletion(
    (tokenResult: ITnsOAuthTokenResult, error) => {
      if (error) {
        console.error("back to main page with error: ");
        console.error(error);
      
      } else {
        console.log("back to main page with access token: ");
        console.log(tokenResult);
       
      }
    }
  );

Even though at manifest file I have added singleTask and path as :/auth,
my above code is not returnning the accesToken

Please help me

**Comment by kcabhish** [comment] 2019-11-18 18:08
I am getting the same issue. In ```TnsOAuthClient's``` object the method loginWithCompletion does not get triggered. The google authentication page pops up, but once the user logs in, it will redirect to google's home page instead of the app.

I was using this video to set up a test project. https://www.youtube.com/watch?v=Ix0bXZeyhK0

**Comment by rishabhgoyal18** [comment] 2019-11-28 14:42
I am also getting the same issue. Stuck at google home page and if I cancel the process it gives error and no request token is generated

**Comment by VitaliyKim** [comment] 2019-11-30 15:50
Same here...

**Comment by rishabhgoyal18** [comment] 2019-11-30 15:55
Working for me now. I had syntax error in .xml file (AndroidManifest.xml). Fixed the error and it is working fine. The mistake was pretty silly in line <action android:name="android.intent.action.VIEW" /> I had typed <action android:name="android.intent.action.view" /> (view in small letters). As android is case sensitive it was not working properly. After using right syntax its working.

**Comment by VitaliyKim** [comment] 2019-11-30 16:10
@rishabhgoyal18 Can you, please, send here the complete content of your <intent-filter> without google client id.

**Comment by rishabhgoyal18** [comment] 2019-12-01 07:19
<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />

				<data android:path="/auth" android:scheme="" />
			</intent-filter>

**Comment by VitaliyKim** [comment] 2019-12-02 17:38
@rishabhgoyal18, thank you.

Unfotunately, couldn't make it work. Switched to https://www.npmjs.com/package/nativescript-google-login

**Comment by rishabhgoyal18** [comment] 2019-12-02 17:40
@VitaliyKim can you share me your code?

**Comment by VitaliyKim** [comment] 2019-12-03 15:39
@rishabhgoyal18 sorry but I've managed to implement it with the other plugin. 
And I think my problem was caused by using wrong client id.
Thank you.

**Comment by thanoseleftherakos** [comment] 2020-02-17 16:08
Same here, any update on this? Thank you

**Comment by alexziskind1** [comment] 2020-02-17 16:10
Closing this issue. Please follow issue template

**Closed by alexziskind1** 2020-02-17 16:10 UTC
