### ISSUE TITLE
Cannot read property 'loginCompletion' of null

### ISSUE THREAD

**Issue by napolev** [alexziskind1/nativescript-oauth2#50] opened 2019-07-05 06:03 UTC
### Which platform(s) does your issue occur on?
- Android
- Target: Android 7.0. API: 24
- Emulator. Pixel 2 API 24

### Please, provide the following version numbers that your issue occurs with:
```
$ tns --version
5.4.2
```
- Cross-platform modules: `"version": "5.2.2"`
(check the 'version' attribute in the `node_modules/tns-core-modules/package.json` file in your project)

- Runtime(s): `"version": "5.2.0"`
(look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)

- Plugin(s): (look for the version numbers in the `package.json` file of your project and paste your dependencies and devDependencies here)

```
    "dependencies": {
        "@angular/animations": "~7.2.0",
        "@angular/common": "~7.2.0",
        "@angular/compiler": "~7.2.0",
        "@angular/core": "~7.2.0",
        "@angular/forms": "~7.2.0",
        "@angular/http": "~7.2.0",
        "@angular/platform-browser": "~7.2.0",
        "@angular/platform-browser-dynamic": "~7.2.0",
        "@angular/router": "~7.2.0",
        "nativescript-angular": "~7.2.1",
        "nativescript-oauth2": "^1.5.3",
        "nativescript-theme-core": "~1.0.4",
        "reflect-metadata": "~0.1.12",
        "rxjs": "~6.3.0",
        "tns-core-modules": "~5.2.0",
        "zone.js": "~0.8.26"
    },
    "devDependencies": {
        "@angular/compiler-cli": "~7.1.0",
        "@nativescript/schematics": "~0.5.0",
        "@ngtools/webpack": "~7.1.0",
        "nativescript-dev-typescript": "~0.8.0",
        "nativescript-dev-webpack": "~0.20.0"
    },
```

### Please, tell us how to recreate the issue in as much detail as possible. 

```
$ git clone https://github.com/napolev/nativescript-oauth2-issue
$ cd nativescript-oauth2-issue
$ npm i
$ tns platform clean android
$ tns devices
$ tns run android [--device <device-id>]
```
Once the app is running on the phone:
1. login with any Google account
2. you will see the access token on the console
3. logout
4. login again
5. you will see some errors on the console from now on any subsequent logins

### Is there any code involved? 

Preview: https://www.youtube.com/watch?v=T-6qj1SAsnk

Github repo: https://github.com/napolev/nativescript-oauth2-issue

I think the problem is on the following file:

/demo-angular/node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js

![Preview](https://i.ibb.co/Bgh3vmn/image.png)

where after the first login/logout, when trying to login again, the variable: `this.authState` is `null` and it is getting asked for: `this.authState.loginCompletion` which throws the exception:

```
Unhandled Promise rejection: Cannot read property 'loginCompletion' of null ;
Zone: <root> ; Task: Promise.then ; Value: TypeError:
Cannot read property 'loginCompletion' of null TypeError: Cannot read property 'loginCompletion' of null
```

**Comment by alexziskind1** [comment] 2019-07-05 12:02
First, thank you for such a detailed issue report - I've never seen such a good issue report!
This is a bug in the way the code verification is being generated by the plugin and needs to be fixed.

**Comment by tlg-265** [comment] 2019-07-05 22:36
You're welcome Alex. I'm glad it helps. Any idea on when this bug will be fixed. In my opinion this is the best plugin for OAuth2 login/authentication out there, so I'm looking forward to the solution. Thanks!

**Comment by napolev** [comment] 2019-07-05 23:07
You're welcome Alex. I'm glad it helps. Any idea on when this bug will be fixed. In my opinion this is the best plugin for OAuth2 login/authentication out there, so I'm looking forward to the solution. Thanks!

**Comment by matthewamarlin** [comment] 2019-07-07 02:44
I too am encountering this issue.

**Comment by danielnitu** [comment] 2019-07-15 10:28
Is there a workaround for this until a fix is pushed?

**Comment by tlg-265** [comment] 2019-07-23 16:33
Hello, is there any update on this?

**Comment by matthewamarlin** [comment] 2019-08-05 09:15
Hi Alex. Please could you get back to us regarding an estimated time as to when this might be fixed, or at least offer us a way to work around the issue as this is a fundamental blocker making the library pretty much unusable.

**Comment by tlg-265** [comment] 2019-08-05 14:17
I'm agree with you @matthewamarlin. In case it is necessary I'm willing to collaborate on this. Probably a group of 3 or 4 fr us can look for the way to fix this issue together and then add it to the project through a pull request.

**Comment by alexziskind1** [comment] 2019-08-07 17:51
Hi folks. 
I've been testing this problem and here are some comments.
1. Demo app Google login on Android returns an access token fine the first time, and randomly other times (without restarting the app). This might be because something is wrong with the google side of things (since the Microsoft login is working fine consistently), or it might be that the expected parameters aren't working. I've tried sending a variable 'state' parameter (even though it's not required), but I get the same issue.
2. I've tried changing the google token endpoint to https://www.googleapis.com/oauth2/v4/token instead of https://accounts.google.com/o/oauth2/token , but this doesn't fix it.
3. Issue with the OP's repo of the problem app: the google config is the same as my sample google config. Which makes me think that many people are using it and perhaps google has throttled this app. I wonder if people are actually using my demo google app instead of generating their own clientID's and what would happen if I turn it off.

At this point I'm still stuck and don't know why this error is randomly being thrown. It might be a throttling issue or something else entirely. 

Other folks' research and potential PR's are welcomed.

**Comment by napolev** [comment] 2019-08-07 18:08
thanks @alexziskind1 for your response. Privately on my side, before submitting this issue, I created my own demo app and the result was exactly the same. At the time I posted the issue I used your Google demo app info just get closer to the original code. So, for sure it is not a throttle problem. By the way, I tried with Facebook as well and everything is perfect with it. The only problem is with Google.

By the way, I don't know if this matters,
on file: /demo-angular/App_Resources/Android/src/main/AndroidManifest.xml

when I tried with my own demo app info from Google, I had to use (exactly as on your code):
```
<data android:scheme="msalf376fa87-64a9-49a1-8b56-e0d48fc0810b"/>
```

If I remove it, then it doesn't work with either, your demo app info or my demo app info.
So, that's a common piece of data that I don't know if it could be related with some potential throttle.
I searched for that code on internet and didn't find it, so, it is kind unique.

What I mean with this is, if that code above is specific for your app info, then maybe I should try again with with the corresponding code specific for my app (which I didn't noticed when created my demo Google app) and then it could be (or not) a throttle problem (then I should test again).

Thanks!

**Comment by alexziskind1** [comment] 2019-08-07 18:10
@napolev `<data android:scheme="msalf376fa87-64a9-49a1-8b56-e0d48fc0810b"/>` is a configuration piece of data that is used with Microsoft login and is not related to the Google login issue.

**Comment by napolev** [comment] 2019-08-07 18:16
Ok @alexziskind1, then the Google issue is not related to your Google demo app only. It is not a throttle issue.

**Comment by Bidou44** [comment] 2019-08-22 15:03
Hi guys, I'm encountering the same problem and this is a huge problem since the whole login is broken. Would be really good to have a workaround...

I don't know if this information is helpful, but on my side I'm not using the Google provider but a custom one of my enterprise.... So it's not directly related to Google I would say....

**Comment by napolev** [comment] 2019-08-22 15:09
@Bidou44 could you please, provide more information about your issue?, maybe similar source code, or screenshots. That will be appreciated at the moment of troubleshooting this. Thanks!

**Comment by alexziskind1** [comment] 2019-08-22 15:15
When has this started happening for you? Is this a new issue? What version are you on? 

Thanks

**Comment by Bidou44** [comment] 2019-08-22 16:15
It is a new application (made in june), and was built with Nativescript 5.4 (we plan to migrate to 6.0 in September/October). Looking at the logs, it seems that it happens randomly on almost all android devices and all Android OS version. I dont know how many devices it is in percent, I would say like 10%, but this is my own estimation (in other words, it is working correctly more or less 90% of the time). Strangely, I didn't see any problem on Ios, so it seems to be android related! It is quite a big issue, because the 10% of the users that can login are giving us one star on the Gogole Play Store.......

I'm not sure that it will help you but here is the stacktrace:
com.tns.NativeScriptException: Calling js method run failed TypeError: Cannot read property 'loginCompletion' of null File: "file:///data/data/xxx/files/app/vendor.js, line: 1, column: 1831942 StackTrace: Frame: function:'e.completeLoginWithTokenResponseError', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1870962 Frame: function:'c', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 2287903 Frame: function:'e.notify', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1308122 Frame: function:'t.onNavigatedFrom', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1776987 Frame: function:'t.raiseCurrentPageNavigatedEvents', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1657882 Frame: function:'t._updateBackstack', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1657230 Frame: function:'t.setCurrent', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1123855 Frame: function:'', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 2204411 Frame: function:'e.invokeTask', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1837202 Frame: function:'t.runTask', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1832368 Frame: function:'t.invokeTask', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1838316 Frame: function:'o.useG.invoke', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1838214 Frame: function:'n.args.(anonymous function)', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1849729 Frame: function:'', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1653029 Frame: function:'e.invoke', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1836517 Frame: function:'t.runGuarded', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1831871 Frame: function:'', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1831483 Frame: function:'run', file:'file:///data/data/xxx/files/app/vendor.js', line: 1, column: 1653088

Additional information: The authentication is done in a Webview. I don't know exactly how the ADFS/OAuth server works because it is done by another departement in my enterprise but if you have a question related to this I can ask them. Note that I will be on holiday tomorrow and will have very limited internet connection so you will have to wait until the 11th September when I get back for an answer.

**Comment by Bidou44** [comment] 2019-08-29 00:48
Any news on this?

**Comment by shubham9237** [comment] 2019-08-30 08:50
Hi guys tam also getting the same problem for google

I have used the same code as provided, 
On second try aim getting the following error

JS: 400 ERRROR Occurred
JS: Unhandled Promise rejection: Cannot read property 'loginCompletion' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'loginCompletion' of null TypeError: Cannot read property 'loginCompletion' of null
JS:     at TnsOAuthLoginSubController.push.../node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js.TnsOAuthLoginSubController.completeLoginWithTokenResponseError file:///node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js:75:0
JS:     at file:///node_modules/nativescript-oauth2/tns-oauth-native-view-controller.js:35:0
JS:     at responseCompletion file:///node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js:62:0
JS:     at file:///node_modules/nativescript-oauth2/tns-oauth-client-connection.js:177:0
JS:     at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:0
JS:     at Zone.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescrip...

please help

**Comment by matthewamarlin** [comment] 2019-08-30 10:02
This issue does not only seem to be related to the Google login provider as other comments have suggested. I am seeing an identical exception when using my own identity server. I'm not sure how to assist further but I am also very keen to get passed this issue.

**Comment by JoshDSommer** [comment] 2019-08-30 11:16
I was experiencing the same issue with Identity Server 4 when using the OIDC configuration 'oidc-full' in our Angular application. when the login with completion error was thrown it prevented login from working.
 
Wrapping it in a setTimeout and using ngZone run out side of angular seems to have fixed it, no more error being thrown.  Still need to mess around with it more, we very may be abled to drop the ngZone or setTimeout. But this setup has eliminated the error and we are able to login and user our app fine.

```
 setTimeout(() => {

        this.client.loginWithCompletion(

          (tokenResult: ITnsOAuthTokenResult, error) => {

            this.ngZone.runOutsideAngular(() => {

              if (error) {

                log('back to main page with error:');

                log(error);

                reject(error);

              } else {

                log('back to main page with access token:');

                log(tokenResult);

                this.setToken(tokenResult);

                resolve(tokenResult);
              }
            });
          }

```

**Comment by alexziskind1** [comment] 2019-08-30 13:13
Thanks for that workaround, Josh. 

Is this a regression after v2 came out? In other words have people started seeing this error after v2 and they weren’t seeing it before v2?

**Comment by JoshDSommer** [comment] 2019-08-30 13:49
I was seeing it before, but hadn't addressed it since we where focusing on iOS.  we have an unrelated(maybe) issue where if we use the configuration 'oidc-none' it shows a broken URL after sign in on android a brief second and it then closes and everything works fine.  

it seems like a couple things are happening in android before values are set correctly. I'll be digging more into it next week.

**Comment by shubham9237** [comment] 2019-09-19 08:07
@JoshDSommer , I tried your solution but still the problem persist

**Comment by matthewamarlin** [comment] 2019-09-19 08:14
I can also confirm the suggested workaround by @JoshDSommer does not work for me either. I have been trying variations on the suggested fix but nothing seems to work. I either keep getting the cannot read property loginCompletion of null, or a different 400 error along side it (after trying variations on the setTimeout or ngZone tricks.)

**Comment by richardscholten73** [comment] 2019-09-19 10:25
Same problem here with identity server 4 on android, workaround by @JoshDSommer did not work for me either. (IOS works fine) 

As a temporary workaround i made a very dirty hack :)
refresh does seem to work after the "failed" login, so te get the tokens i call refresh if tokenResult is null or undefined

```

public login(): Promise<Tokens> {
    return new Promise<Tokens>((resolve, reject) => {
      this._client.loginWithCompletion(
        (tokenResult: ITnsOAuthTokenResult, error) => {
          if (error) {
            console.error(error);
            reject(error);
          } else {
            if (tokenResult) {
              this.silentRefresh(tokenResult);
              this._tokens = new Tokens(tokenResult.accessToken, tokenResult.idToken, tokenResult.refreshToken);
              resolve(this._tokens);
            } else {
              //FIXME: hack for bug in nativescript-oauth2 library https://github.com/alexziskind1/nativescript-oauth2/issues/50
              this.refresh()
                .then(tokens => {
                  resolve(tokens);
                })
                .catch(error => {
                  reject(error);
                });
              //End hack
            }
          }
        }
      );
    });
  }
```


Anyone got a better workaround?

**Comment by Bidou44** [comment] 2019-09-20 06:38
I also tried @JoshDSommer's workaround but it didn't work for me neither.
Will try yours @richardscholten73 as soon as possible...

**Comment by matthewamarlin** [comment] 2019-09-20 15:01
@richardscholten73 Please could you provide a more complete example or possibly a link to a repo, as i tried doing what you suggested above with no success (of course i have to assume some things).

**Comment by richardscholten73** [comment] 2019-09-27 11:08
Unfortunately my workaround is working only in a few situations, (calling the login from a method in a component/page) Now trying the same thing from a page guard and failing horribly because of this bug. It's wreaking havoc on the application when the error occurs, the application stops working properly because of this.

Running out of options here, the only thing left is building our own solution from scratch and i really don't want to spent that amount of time...

@alexziskind1 Is this being addressed? Could you give us an estimate timeframe when this issue will be resolved?

**Comment by Bidou44** [comment] 2019-09-27 14:25
@richardscholten73 Well that's a bad news. I didn't deploy the fix for now, but I had a lot of hope in your workaround... For us it's also a very big issue since a lot of our users cannot login !

I also notice another issue that generates exactly the same issue: a blank page. It seems to happen when the server's certificate cannot be validate (don't ask why it happens, for most of the user it's working, but for some the validation seems to not be possible).

So if we summarize, the loginWithCompletion method starts a WebView internally and when a failure occurs, a blank page is displayed and it's not possible for the user to do anything else... So my question is: would it be possible to do a try-catch in this loginWithCompletion method and close the browser if something bad happens? Or maybe, give the exception back with a reference on the webview so that we can close it ourself?

**Comment by napolev** [comment] 2019-10-04 19:01
Hi team, any update on this? any attempt of making this to work properly going on?
What about taking a look to the code of this other plugin: "nativescript-social-login"
https://github.com/mkloubert/nativescript-social-login/blob/master/src/SocialLogin.android.ts
and taking from there the way they use to handle the `Google` login?

**Comment by napolev** [comment] 2019-10-04 19:23
By the way, if there are people here with knowledge about Android/Java programming that want to create a real time collaboration chat group to talk (via Skype, Slack, Zoom, or whatever) in order to solve this issue definitely please click on the Rocket. I have worked with Android/Java in the past so I can help. I think talking about that in real time and putting all of our mental energy on it we can solve it in couple of days, then we can create a pull request with our proper approach. In my opinion this is the best plugin out there so it worth it. If you have not experience with Android/Java programming or are not able to participate on a real time collaboration chat group in order to solve this, please, do not click the rocket to avoid confusions. You can click whatever other icon if you want :) I have been waiting for the solution of this issue for months now and I think it should not be difficult to solve it but I prefer to solve it with more developers at the same time because one developer could see things other developers don't thing and vice versa. I think it is possible, so, let's go for it! ;)

**Comment by alexziskind1** [comment] 2019-10-04 20:59
@napolev I’m afraid the other plugin you referenced has several native dependencies - exactly the reason this plugin is preferred by many.
To your next point, my android abilities are very limited and I would absolutely welcome any help from the community to solve this. So far there are many complaints, but nobody is helping and I hope to see some involvement.

**Comment by alexziskind1** [comment] 2019-10-04 21:00
And a Slack channel for more real-time collab is a great idea!

**Comment by napolev** [comment] 2019-10-05 15:37
Alex I went ahead and created a [Slack Channel](https://join.slack.com/t/nativescript-hq/shared_invite/enQtNzg3MjYyNDMwMzkwLTViM2Q1OTdhZjgwYWJhNjJkYmVjOTdlMTI4MjEyZDA5ZGJhMjQ0MDY3ZTkwNWJlNGMwNWJlM2I0OTg0OGU4OGQ) for this issue. You are welcome to join it if you want but not necessary, I understand you are very busy with other projects.

I will get involved on this issue fix only if there are 2 or 3 more experienced Java/Android developers willing to work on it intensively for up to 2 days. I also don't have too much free time and cannot be in risk of wasting more than that time to fix the issue. That's why I want extra help just to be sure that it will be solved in that period of time. Also, in order to do a pull request I want that the approach / solution be agreed by more than one developer because maybe there are things that I cannot notice that other developers can.

Only if you are a Java/Android developer and are able to work on this for up to 2 days intensively with others in order to fix this issue, you can join to this [Slack Channel](https://join.slack.com/t/nativescript-hq/shared_invite/enQtNzg3MjYyNDMwMzkwLTViM2Q1OTdhZjgwYWJhNjJkYmVjOTdlMTI4MjEyZDA5ZGJhMjQ0MDY3ZTkwNWJlNGMwNWJlM2I0OTg0OGU4OGQ). Otherwise, please, don't join it.

In the other hand, if you get the right solution for it, please, do a pull request.

Thank you!

**Comment by alexziskind1** [comment] 2019-10-05 17:37
Thanks for setting this up @napolev

**Comment by EddyVerbruggen** [comment] 2019-10-09 18:45
Hi all, can some of you please update the repo and see if [this commit](https://github.com/alexziskind1/nativescript-oauth2/commit/4b15ede5e6b4b9366afcaf5e128222cdce54969b) fixes the issue for you? TIA!

**Comment by alexziskind1** [comment] 2019-10-10 01:56
Thanks @EddyVerbruggen ! I've tested this before and after your fix and now I don't get the null error happening. @napolev can you please test the latest code and see if this works for you as well?

**Comment by zeuscronos** [comment] 2019-10-10 03:19
@alexziskind1, unfortunatelly the issue persists based on my experiments (the behavior for me is exactly the same as before). I tried multiple times. I also removed the directory: `node_modules` and then: `$ npm i` with the new version: `2.2.1`. Also did `$ tns platform clean android` but no luck. This is the repository I'm trying (the same as before with the package update): https://github.com/napolev/nativescript-oauth2-issue. Has anybody else tried with the package update? Thanks @EddyVerbruggen.

**Comment by napolev** [comment] 2019-10-10 03:22
@alexziskind1, unfortunatelly the issue persists based on my experiments (the behavior for me is exactly the same as before). I tried multiple times. I also removed the directory: `node_modules` and then: `$ npm i` with the new version: `2.2.1`. Also did `$ tns platform clean android` but no luck. This is the repository I'm trying (the same as before with the package update):
https://github.com/napolev/nativescript-oauth2-issue.
Has anybody else tried with the package update?

Thanks @EddyVerbruggen!

**Comment by EddyVerbruggen** [comment] 2019-10-10 06:06
Hi @napolev, this fix has not been released to npm yet, so you’ll need to test this from github :)

**Comment by alexziskind1** [comment] 2019-10-10 12:12
@napolev I added instructions on getting this set up for local tests in the README contributing quick steps- https://github.com/alexziskind1/nativescript-oauth2/blob/master/README.md#contributing-quick-steps

Since Eddy’s fix helps, I’ll push that to npm today, but will keep this issue open for now. Let me know if you were able to set up and run the plugin locally

**Comment by napolev** [comment] 2019-10-11 03:29
I followed the instructions here:

https://github.com/alexziskind1/nativescript-oauth2#contributing-quick-steps

but got the following error:

![image](https://user-images.githubusercontent.com/3321307/66622322-cdbb0980-ebac-11e9-87eb-02fece693d21.png)

That doesn't mean there is something wrong with the recent updates, so I don't want to distract the attention with this.

Since the new updates will be published on https://www.npmjs.com eventually, I will wait for that.

Thanks!

**Comment by alexziskind1** [comment] 2019-10-12 23:55
@napolev please check version 2.2.2 on npm and see if this helps your issue

**Comment by napolev** [comment] 2019-10-13 00:20
Awesome!, just checked the latest version`2.2.2` and it is working fine now. Good job guys. Thanks @alexziskind1, @EddyVerbruggen and the rest of the people here analyzing the situation from different points of view 😉

**Comment by alexziskind1** [comment] 2019-10-13 02:15
Good to hear! All the thanks to @eddyverbruggen for this

**Closed by alexziskind1** 2019-10-13 02:15 UTC
Labels: bug

**Comment by shubham9237** [comment] 2019-10-16 05:22
This is the error cam getting now


JS: Unhandled Promise rejection: _this.refresh is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: _this.refresh is not a function TypeError: _this.refresh is not a function
JS:     at file:///src/app/item/item.service.ts:72:23
JS:     at TnsOAuthLoginSubController.push.../node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js.TnsOAuthLoginSubController.completeLoginWithTokenResponseError (file:///node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js:86:0)
JS:     at file:///node_modules/nativescript-oauth2/tns-oauth-native-view-controller.js:39:0
JS:     at responseCompletion (file:///node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js:71:0)
JS:     at file:///node_modules/nativescript-oauth2/tns-oauth-client-connection.js:177:0
JS:     at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:0)
JS:     at Zone.push.../node_modules/nativescript-angu...
JS: Unhandled Promise rejection: Cannot read property 'loginCompletion' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'loginCompletion' of null TypeError: Cannot read property 'loginCompletion' of null
JS:     at TnsOAuthLoginSubController.push.../node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js.TnsOAuthLoginSubController.completeLoginWithTokenResponseError (file:///node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js:84:0)
JS:     at file:///node_modules/nativescript-oauth2/tns-oauth-native-view-controller.js:39:0
JS:     at responseCompletion (file:///node_modules/nativescript-oauth2/tns-oauth-login-sub-controller.js:66:0)
JS:     at file:///node_modules/nativescript-oauth2/tns-oauth-client-connection.js:177:0
JS:     at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:0)
JS:     at Zone.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescrip...

**Comment by napolev** [comment] 2019-10-16 05:26
@shubham9237 could you please provide a simplified code that generates the same error?, if you want you can fork from my initial code. Thanks!

**Comment by shubham9237** [comment] 2019-10-16 05:39
Actually the error is only on android I tested it on IOS , and it works perfectly fine on IOS, but the error continues on android

1. Try login through gmail in android device/emulator , at first it works fine
2.Try again and now when redirected to app it throughs the error

I have upgraded to 2.2.2 nativescript oath version

Iam using Mac Book pro with the following configurations

npm(6.9.0)
Angular CLI: 8.0.1
Node: 10.16.0
Angular: 8.2.11
nativescript-oauth2 : 2.2.2


  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "nativescript-angular": "~8.2.0",
    "nativescript-background-http": "^4.2.0",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-oauth2": "^2.2.2",
    "nativescript-orientation": "^2.2.3",
    "nativescript-social-login": "^4.0.1",
    "nativescript-social-share": "^1.5.2",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toasty": "^2.0.1",
    "nativescript-ui-listview": "^7.1.0",
    "nativescript-ui-sidedrawer": "^7.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.1.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^0.7.1",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.2.0",
    "typescript": "~3.5.3"
  },

**Comment by napolev** [comment] 2019-10-16 05:46
@shubham9237 do you think you could create a dummy repo on GitHub so I can clone that repo and test real quick? Ideally maybe you can put your changes on top of some known repo like the one I posted initially or this one: https://github.com/alexziskind1/nativescript-oauth2/tree/master/demo-angular. In other words, not just dumping the project on a 1-commit repo, so we can trace the differences better.

**Comment by shubham9237** [comment] 2019-10-16 05:47
@napolev sir, wait I will create a new dummy project and if their is the same error I will post it on GitHub :)

**Comment by zeuscronos** [comment] 2019-10-16 06:14
thank you @shubham9237!

**Comment by napolev** [comment] 2019-10-16 06:15
thank you @shubham9237!

**Comment by shubham9237** [comment] 2019-10-16 07:18
@napolev sir, I tried in new demo app and the gmail login works fine , I think iam messing something in my code but iam not getting whats wrong here

    public onTapLogin(bymenasOf) {
        this.itemService
            .tnsOauthLogin(bymenasOf)
            .then((result: ITnsOAuthTokenResult) => {
              console.log("back to login component with token " + result.accessToken);
              let url="";
              let id="";
            if(bymenasOf=="facebook"){
                url="https://graph.facebook.com/me/?fields=id,name&access_token="+result.accessToken;
            }else{
                url="https://www.googleapis.com/oauth2/v1/tokeninfo?access_token="+result.accessToken;
            }
              this.getdata(url).subscribe((result) => {
                if(bymenasOf=="facebook"){
                    id=result["id"];
                }else{
                    id=result["user_id"];
                }
                this.itemService.showLoader();
                  this.getdata("http://portal.smallborrowing.com/api/check_user.php?ref="+bymenasOf+"&auth="+id).subscribe((result) => {
                  if(result[0]["status"]=="success"){
                        this.itemService.userFound=result;
                        console.log(this.itemService.userFound);
                        this.itemService.addUserData();
                        console.log("done");
                                this.routerExtensions
                                .navigate(["/home"],
                                {
                                    animated: true,
                                    transition:
                                    {
                                        name: 'fade',
                                        duration: 500,
                                        curve: 'linear'
                                    },
                                    clearHistory:true
                                } )
                                .then(() => this.itemService.setLocalBoolean("isLoggedIn", true))
                                .catch(err => console.log("error navigating to /home item.component.ts: " + err));
                    }else{
                        this.itemService.auth_id=id;
                        this.itemService.auth_type=bymenasOf;
                                this.routerExtensions
                                .navigate(["/register"],
                                {
                                    animated: true,
                                    transition:
                                    {
                                        name: 'fade',
                                        duration: 500,
                                        curve: 'linear'
                                    },
                                    clearHistory:false
                                } )
                                .then(() => console.log("navigated to /register"))
                                .catch(err => console.log("error navigating to /register: " + err));
                    }
              }, (error) => {
                  console.log(error);
              });


            }, (error) => {
                console.log(error);
            });
            })
            .catch(e => console.log("Main Error: " + e));
      }



this is the code when users hits the login with google or fb where iam passing bymeansOf as a variable of Facebook or google

**Comment by shubham9237** [comment] 2019-10-16 07:20
public tnsOauthLogin(providerType): Promise<ITnsOAuthTokenResult> {
        this.client = new TnsOAuthClient(providerType);

        return new Promise<ITnsOAuthTokenResult>((resolve, reject) => {

          this.client.loginWithCompletion(
            (tokenResult: ITnsOAuthTokenResult, error) => {

              if (error) {
                // console.error("back to main page with errorr: ");
                // console.error(error);
                reject(error);
              } else {
                if(tokenResult){
                  // console.log("Token result in else part"+tokenResult);
                  // console.log("back to main page with access token using ng zoen: ");
                  // console.log("token result in item.service.ts "+tokenResult);
                  resolve(tokenResult);
                }else{
                  this.toast("Server error occured, please try later!")
                  this.refresh().then(tokens=>{
                    resolve(tokens);
                  }).catch(error=>{
                    reject(error);
                  })
                }
              }

            }
          );
        });
      }



and this is the code in service

**Comment by napolev** [comment] 2019-10-16 13:01
@shubham9237, please, try to provide a repository as I told you before. If that's not possible, then take as base code, the "demo-angular" project that is on the official repo and build your app incrementally on top of it. If at some point you arrive to an error then publish that repo so we can look at it. You just told: "I tried in new demo app and the gmail login works fine", then build your app based on that, probably you won't get any errors. Thanks!

**Comment by shubham9237** [comment] 2019-10-17 05:46
Ohk sir! ;)

**Comment by aldoabazi** [comment] 2019-11-06 11:09
I had the loginCompletion error too, updated to 2.2.2 and works great on my android emulator, but not in my phone(galaxy s9+). After login, logout and login again , loginCompletion error with null access token pops out.

**Comment by vincentpalita** [comment] 2019-11-20 08:58
@aldoabazi you should check again with the new version 2.3.0 that got published yesterday! It fixed my issues completely :)
